version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "cd ts_practice && npm start"
    container_name: ts_practice
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./:/usr/src
